### PR TITLE
Fix broken link in Readme

### PR DESCRIPTION
**Pull request by abel-bzz**
## Description

Fixes # (issue)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I wrote unit tests for my code _(if tests is required for my changes)_
- [x] I have made changes in `CHANGELOG.md` file

### CODE REVIEW

**Comment by jetexe** [comment]
Hi!
Did you test it? Current link is correct and works fine, but your suggestion is not.

Docker hub image is [avtodev/markdown-lint](https://hub.docker.com/r/avtodev/markdown-lint/tags)

**Comment by abel-bzz** [comment]
Hi @jetexe Yeah I tried here: https://github.com/bzah/git-training/actions/runs/1805127705/workflow

However, I only tried the second suggestion below `#Or using current repository as action:`
I though both links were broken but should have tried the first one as well !

**Comment by jetexe** [comment]
Oh. I see. You brake part with docker image, but fix github action

**Comment by jetexe** [comment]
My apologies, you are absolutely right

**Pull request merged**
